package su.nightexpress.excellentenchants.enchantment;

import org.jetbrains.annotations.NotNull;
import su.nightexpress.excellentenchants.EnchantsFiles;
import su.nightexpress.excellentenchants.bridge.DistributionSettings;
import su.nightexpress.nightcore.config.FileConfig;
import su.nightexpress.nightcore.configuration.AbstractConfig;
import su.nightexpress.nightcore.configuration.ConfigProperty;
import su.nightexpress.nightcore.configuration.ConfigTypes;

import java.nio.file.Path;

public class DistributionConfig extends AbstractConfig implements DistributionSettings {

    @NotNull
    public static DistributionConfig load(@NotNull Path dataDir) {
        FileConfig fileConfig = FileConfig.load(dataDir.toString(), EnchantsFiles.FILE_DISTRIBUTION);
        DistributionConfig settings = new DistributionConfig();
        fileConfig.edit(settings::load);
        return settings;
    }

    @Override
    public void load(@NotNull FileConfig config) {
        if (config.contains("Custom_Namespace.Enabled")) {
            config.set("Core.Use-Minecraft-Namespace", !config.getBoolean("Custom_Namespace.Enabled"));
            config.remove("Custom_Namespace.Enabled");
        }

        super.load(config);
    }

    private final ConfigProperty<Boolean> useMinecraftNamespace = this.addProperty(ConfigTypes.BOOLEAN, "Core.Use-Minecraft-Namespace",
        false,
        "Controls whether to use 'minecraft' namespace for the Excellent Enchantments.",
        "[*] WARNING: NOT RECOMMENED TO CHANGE. MAY BE REMOVED IN FUTURE RELEASES. SUPPORT VOID IF SET ON 'TRUE'.",
        "[*] WHEN CHANGED, ALL EXISTING EXCELLENT ENCHANTMENTS ON ITEMS WILL BE DELETED FOREVER.",
        "[*] Server reboot required.",
        "[Default is false]"
    );

    private final ConfigProperty<Boolean> distributionEnchanting = this.addProperty(ConfigTypes.BOOLEAN, "Distribution.Enchanting_Table",
        true,
        "Controls whether excellent enchants can be found in an enchanting table or use to enchant items generated by loot tables.",
        "https://minecraft.wiki/w/Enchanting#Enchanting_table",
        "[*] Server reboot required.",
        "[Default is true]"
    );

    private final ConfigProperty<Boolean> distributionTrading = this.addProperty(ConfigTypes.BOOLEAN, "Distribution.Trading",
        true,
        "Controls whether excellent enchants can be sold by villagers.",
        "https://minecraft.wiki/w/Trading#Librarian",
        "[*] Server reboot required.",
        "[Default is true]"
    );

    private final ConfigProperty<Boolean> distributionMobEquipment = this.addProperty(ConfigTypes.BOOLEAN, "Distribution.Mob_Equipment",
        true,
        "Controls whether excellent enchants can be found on spawned mobs' equipment.",
        "https://minecraft.wiki/w/Armor#Armor_equipped_on_mobs",
        "[*] Server reboot required.",
        "[Default is true]"
    );

    private final ConfigProperty<Boolean> distributionTradeEquipment = this.addProperty(ConfigTypes.BOOLEAN, "Distribution.Trade_Equipment",
        true,
        "Controls whether excellent enchants can be found on equipment sold by villagers.",
        "https://minecraft.wiki/w/Trading#Trade_offers",
        "[*] Works only if Villager Trade Rebalance is DISABLED.",
        "[*] Server reboot required.",
        "[Default is true]"
    );

    private final ConfigProperty<Boolean> distributionRandomLoot = this.addProperty(ConfigTypes.BOOLEAN, "Distribution.Random_Loot",
        true,
        "Controls whether excellent enchants can be found on naturally generated equipment from loot tables.",
        "https://minecraft.wiki/w/Loot_table",
        "[*] Server reboot required.",
        "[Default is true]"
    );

    public boolean isUseMinecraftNamespace() {
        return this.useMinecraftNamespace.get();
    }

    @Override
    public boolean isEnchantingEnabled() {
        return this.distributionEnchanting.get();
    }

    @Override
    public boolean isTradingEnabled() {
        return this.distributionTrading.get();
    }

    @Override
    public boolean isMobEquipmentEnabled() {
        return this.distributionMobEquipment.get();
    }

    @Override
    public boolean isTradeEquipmentEnabled() {
        return this.distributionTradeEquipment.get();
    }

    @Override
    public boolean isRandomLootEnabled() {
        return this.distributionRandomLoot.get();
    }
}
