main: su.nightexpress.excellentenchants.EnchantsPlugin
bootstrapper: su.nightexpress.excellentenchants.bridge.paper.PaperEnchantsBootstrap
name: ExcellentEnchants
version: '${project.version}'
description: A lot of new enchantments properly integrated into the server!
api-version: '1.21'
folia-supported: true
dependencies:
  bootstrap:
    nightcore:
      load: BEFORE
      required: true
  server:
    nightcore:
      load: BEFORE
      required: true
    ProtocolLib:
      load: BEFORE
      required: false
    packetevents:
      load: BEFORE
      required: false
    PlaceholderAPI:
      required: false
    MythicMobs:
      required: false
