main: su.nightexpress.excellentenchants.EnchantsPlugin
version: '${project.version}'
name: ExcellentEnchants
author: NightExpress
desciption: A lot of new enchantments properly integrated into the server!
depend: [ nightcore ]
softdepend:
  - ProtocolLib
  - packetevents
  - PlaceholderAPI
  - MythicMobs
api-version: 1.21
load: STARTUP